### PR TITLE
travis/appveyor: support building wheels for python 3.7

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/theacodes/cmarkgfm/issues/9

### CODE REVIEW

**Comment by anthrotype** [comment]
hm, looks like Travis and Appveyor CI builds are not activated for pull requests... Well, I guess we'll discover if this works once @theacodes merges this to master.

**Comment by theacodes** [comment]
Let's see indeed!

**Comment by anthrotype** [comment]
thanks! If you prefer not to enable CI builds on PRs, it would be good at least to place the Travis and Appveyor badges with the respective URLs in the README so they are shown in repo's home page.

I managed to find the Travis link:
https://travis-ci.org/theacodes/cmarkgfm-wheels

but I don't know which is the link to the Appveyor page for this project.

**Comment by anthrotype** [comment]
the non-py37 builds seems to be failing on Travis with some ssl errors. Maybe they will fix themselves if you simply update the git submodule of multibuild to the latest master branch (or even the `devel` branch).

Would you like me to do that in another PR (but then again you'll have to click merge so that the build will trigger from master, etc.), or you just do it?

**Comment by theacodes** [comment]
I'm currently traveling and afk, but I went ahead and added you as a collaborator in case you wanna go for it. :)

**Comment by anthrotype** [comment]
thank you @theacodes!
do you know what's the URL of the Appveyor page for cmarkgfm-wheels project?

**Comment by theacodes** [comment]
Not off the top of my head, but it is totally possible it's listed under
jonparrott/cmarkgfm-wheels

**Comment by anthrotype** [comment]
This https://ci.appveyor.com/project/jonparrott/cmarkgfm-wheels ?

Looking at the build history, it seems it hasn't run a new build in about 3 months so I don't think it's configured to link with this repository.

**Comment by anthrotype** [comment]
looking at the travis ci build logs, I see two distinct kinds of failures, one of which is benign.

For all the builds for which v0.4.2 already has a wheel published on PyPI, we get a message like this:
https://travis-ci.org/theacodes/cmarkgfm-wheels/jobs/406297172#L504
  
> Skipping cmarkgfm, due to already being wheel

and then later on another script `multibuild/supported_wheels.py` fails for it cannot seem to find the requested wheel file. This is OK, because we don't want to attempt to reupload to PyPI wheel files with the same 0.4.2 version, but only add the 3.7 wheels.

The other failure only affects the new 3.7 builds:

https://travis-ci.org/theacodes/cmarkgfm-wheels/jobs/406297182#L649

> HTTPError: 403 Client Error: The user '[secure]' isn't allowed to upload to project 'cmarkgfm'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/

It seems like twine cannot get the correct username. I don't see a `TWINE_USERNAME` environment variable exported anywhere in the .travis.yml env.

https://github.com/theacodes/cmarkgfm-wheels/blob/b0a6539cecb6857095ad9289ad038356a2081a61/.travis.yml#L13-L19

there is only a secure encrypted variable set (possibly the password?).
What I usually do in other projects where I need to call twine for uploading some wheels is:
1) export a non-encrypted TWINE_USERNAME in the global env
2) store the secure TWINE_PASSWORD environment variable in the project's Travis CI settings (i.e. not shown inside the .travis.yml, not even as a 'secure' string). For example:

https://github.com/adobe-type-tools/psautohint/blob/7fc9657ff39105f61679d409502fe58cb63a69c5/.travis.yml#L27-L28

Or alternatively, I use the command-line tool `travis encrypt` to add the TWINE_PASSWORD as a secure global variable, like here:

https://github.com/fonttools/ufoLib2/blob/bc7ab3af790ac4205539db8eb2dd9e19d0c96fda/.travis.yml#L6-L7

**Comment by theacodes** [comment]
Thanks for all of this, @anthrotype, you rock.

I've updated the secrets for Travis and AppVeyor to point to my new PyPI account. I also created a new AppVeyor account. :)

Builds:
- https://travis-ci.org/theacodes/cmarkgfm-wheels/builds/407798230
- https://ci.appveyor.com/project/theacodes/cmarkgfm-wheels/build/1.0.1

Hopefully these work.

**Comment by anthrotype** [comment]
seems to be working! 👍

**Comment by theacodes** [comment]
Indeed! [Look at all those wheels!](https://pypi.org/project/cmarkgfm/0.4.2/#files)

Thanks again, @anthrotype!

**Pull request merged**
