### PR TITLE
Various hygiene tweaks (e.g. use subfolder for Travis scripts)

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by dhermes** [comment]
@theacodes I'm surprised to see the [MinGW install][1]. Any particular reason why it was needed?

Also, when will you drop 3.4 support? Now :grinning:?

[1]: https://github.com/theacodes/cmarkgfm-wheels/blob/e974511f18ce8fd49c73379919a75b7609c8fc29/appveyor.yml#L56

**Comment by dhermes** [comment]
Sorry I just saw the text of https://github.com/theacodes/cmarkgfm-wheels/commit/b0a6539cecb6857095ad9289ad038356a2081a61

> update multibuild submodule to latest 'devel' branch

Did you want to be using `devel` or `master` for `multibuild`? The [README][1] for `multibuild` says

> We try to keep the `master` branch stable and do testing and development in the `devel` branch. From time to time we merge `devel` into `master`.

[1]: https://github.com/matthew-brett/multibuild/blob/951b6c64f01853cf2569000bb30ecd01a16bba0b/README.rst#multibuild-development

**Comment by dhermes** [comment]
Eek, https://ci.appveyor.com/project/theacodes/cmarkgfm-wheels/builds/20802755 was running and I couldn't cancel it. Good thing that `test_env\Scripts\python --version` error was in there (it should've been `..\test_env\Scripts\python --version`).

It occurs to me that the `twine upload` lines are a bit dangerous, even though you do use `--skip-existing`.

----

Also, why is Travis not running for PRs? https://travis-ci.org/theacodes/cmarkgfm-wheels/pull_requests

**Comment by anthrotype** [comment]
>  I'm surprised to see the MinGW install. Any particular reason why it was needed?

because building cmarkgfm library for Windows Python 2.7 fails when using the default compiler toolchain MSVC 2008, as that's too old

**Comment by theacodes** [comment]
Really no CI should be running for PRs. This isn't supposed to be a repo that's setup for contribution, just as a convenient way to separately store our deploy script.

@dhermes do you think this is ready to merge?

**Comment by dhermes** [comment]
@theacodes I think it's ready to merge, though I'd also like to discuss a different approach (than `twine`) if you have time. In [`bezier-wheels`][1] I upload to GCS after the build.

[1]: https://github.com/dhermes/bezier-wheels

**Comment by theacodes** [comment]
Thanks, @dhermes!

**Pull request merged**
